"""
Django settings for HairBraider project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(bh+zdg%^9tw^8h&0)w=2sp-r4i=uikgvj^q25668p=a32#at+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'main',
    'users',
    'orders',
    'reviews',
    'about',

    # telegram
    'django_telegram_login',
    # для авторизации через телеграм
    'corsheaders',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # для авторизации через телеграм
    'corsheaders.middleware.CorsMiddleware',
]


# для авторизации через телеграм
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

ROOT_URLCONF = 'HairBraider.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HairBraider.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cr96562_HB',
#         'USER': 'cr96562_HB',
#         'PASSWORD': '89526136205Sa',
#         'HOST': '127.0.0.1',
#         'PORT': 3306,
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Krasnoyarsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']  # Папка, где лежат CSS/JS/изображения

STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = '/'

LOGIN_REDIRECT_URL = 'main:index'  # URL по умолчанию после входа
LOGOUT_REDIRECT_URL = 'main:index'  # URL после выхода


DATE_INPUT_FORMATS = ['%d.%m.%Y', '%Y-%m-%d']
TIME_INPUT_FORMATS = ['%H:%M', '%I:%M %p']


# Telegram settings
TELEGRAM_BOT_NAME = 'HairBraiderbot'  # Имя вашего бота без @
TELEGRAM_BOT_TOKEN = "7993455435:AAGO0f39bPs9v_Wpgqb4kzBAXAfC0lo1gic"
        
TELEGRAM_LOGIN_REDIRECT_URL = 'https://adequately-opportune-surfbird.cloudpub.ru/user/registration/'  # Куда перенаправлять после успешного входа


CSRF_TRUSTED_ORIGINS = [
    'https://adequately-opportune-surfbird.cloudpub.ru',
    # Другие доверенные источники
]


YANDEX_CAPTCHA_PUBLIC_KEY = 'ysc1_jsQ0rk3kAUC3HVkh9j5PwHeHLiykKYa8pIi9EmIX448f6251'
YANDEX_CAPTCHA_PRIVATE_KEY = 'ysc2_jsQ0rk3kAUC3HVkh9j5PCe9gqzLaVunauUT0VGzF14ee453a'