# Generated by Django 5.2.4 on 2025-08-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_available_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, default=False, null=True, related_name='products', to='main.color', verbose_name='Доступные цвета'),
        ),
    ]
