# Generated by Django 5.2.4 on 2025-08-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_available_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='main.color', verbose_name='Доступные цвета'),
        ),
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Дата',
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('freely', models.BooleanField(default=True, verbose_name='Свободно? ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='main.availabledate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
                'unique_together': {('date', 'time')},
            },
        ),
    ]
