# Generated by Django 5.2.4 on 2025-08-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_available_colors_availabledate_and_more'),
        ('orders', '0006_availabledate_alter_appointment_date_availabletime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='availabletime',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='AvailableDate',
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
    ]
