# Generated by Django 5.2.4 on 2025-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
