# Generated by Django 5.2.4 on 2025-08-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_make_comment',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Может оставлять коммент?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует!!!'}, max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
