# Generated by Django 5.2.4 on 2025-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edit_name',
            field=models.BooleanField(default=False, verbose_name='Изменять имя?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='edit_username',
            field=models.BooleanField(default=False, verbose_name='Изменять имя пользователя?'),
        ),
    ]
