# Generated by Django 5.2.4 on 2025-07-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
    ]
