# Generated by Django 5.2.4 on 2025-08-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_has_make_comment_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_make_comment',
        ),
        migrations.AddField(
            model_name='user',
            name='count_comments',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Колличество комментариев может оставить'),
        ),
    ]
