# Generated by Django 5.2.4 on 2025-08-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_phone_verified_user_phone_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
    ]
