# Generated by Django 5.2.4 on 2025-08-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_phone_verified_callcheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallCheck',
        ),
    ]
