# Generated by Django 5.2.4 on 2025-08-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_callcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
