# Generated by Django 5.2.4 on 2025-08-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_telegram_data_user_telegram_auth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_auth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
