# Generated by Django 5.2.4 on 2025-08-12 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Дата',
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('freely', models.BooleanField(default=True, verbose_name='Свободно? ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='orders.availabledate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('colors', models.ManyToManyField(blank=True, to='main.color', verbose_name='Выбранные цвета')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabledate', verbose_name='Дата')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabletime', verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'unique_together': {('date', 'time')},
            },
        ),
    ]
