# Generated by Django 5.2.4 on 2025-07-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='client_phone',
            new_name='phone',
        ),
    ]
