# Generated by Django 5.2.4 on 2025-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='colors',
            field=models.ManyToManyField(to='main.color', verbose_name='Выбранные цвета'),
        ),
    ]
