# Generated by Django 5.2.4 on 2025-07-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_client_name_appointment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='freely',
            field=models.BooleanField(default=True, verbose_name='Свободно? '),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabledate', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabletime', verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='availabledate',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='orders.availabledate', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
    ]
