# Generated by Django 5.2.4 on 2025-08-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('orders', '0003_appointment_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='colors',
            field=models.ManyToManyField(blank=True, to='main.color', verbose_name='Выбранные цвета'),
        ),
    ]
