# Generated by Django 5.2.4 on 2025-08-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_available_colors_availabledate_and_more'),
        ('orders', '0004_alter_appointment_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.availabledate', verbose_name='Дата'),
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='availabletime',
            unique_together=None,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.availabletime', verbose_name='Время'),
        ),
        migrations.DeleteModel(
            name='AvailableDate',
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
    ]
