# Generated by Django 5.2.4 on 2025-08-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_appointment_date_remove_availabletime_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Дата',
                'unique_together': {('date',)},
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabledate', verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('freely', models.BooleanField(default=True, verbose_name='Свободно? ')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='orders.availabledate', verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Время',
                'verbose_name_plural': 'Время',
                'unique_together': {('date', 'time')},
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.availabletime', verbose_name='Время'),
        ),
    ]
